# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43dd5456f8a926a1f5336ad6f52d8ab88966449160e32897a95c1ffb6e80f90305446986c8bd3b6b4490e283f38992dbcb51e647b75d6595cefc0ce37769cf2f

test:
  secret_key_base: 6af34ffeed7364f05dc38f7b1b1710caed8b26e24c8ee5a3e81831e270ef429570cf3087281fe4db53cff33861cfc282a48d78ae45b9efdf0c1f893a2376d9f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
